"""empty message

Revision ID: 4e40795aa172
Revises: e9690ecc0d7e
Create Date: 2020-05-13 18:50:24.021184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e40795aa172'
down_revision = 'e9690ecc0d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'quantity')
    # ### end Alembic commands ###
