"""empty message

Revision ID: 895c73162b6a
Revises: 
Create Date: 2020-05-14 14:19:41.720009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895c73162b6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('insight_id_in', sa.Integer(), nullable=True))
    op.drop_constraint('lots_session_id_in_fkey', 'lots', type_='foreignkey')
    op.create_foreign_key(None, 'lots', 'insights', ['insight_id_in'], ['id'])
    op.drop_column('lots', 'session_id_in')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('session_id_in', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lots', type_='foreignkey')
    op.create_foreign_key('lots_session_id_in_fkey', 'lots', 'insights', ['session_id_in'], ['id'])
    op.drop_column('lots', 'insight_id_in')
    # ### end Alembic commands ###
