"""empty message

Revision ID: e5a05ca03583
Revises: 4e40795aa172
Create Date: 2020-05-13 19:34:39.559169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a05ca03583'
down_revision = '4e40795aa172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('institution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lots', 'institutions', ['institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lots', type_='foreignkey')
    op.drop_column('lots', 'institution_id')
    # ### end Alembic commands ###
