"""empty message

Revision ID: e9690ecc0d7e
Revises: 
Create Date: 2020-05-13 18:44:24.313706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9690ecc0d7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutions', sa.Column('active', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutions', 'active')
    # ### end Alembic commands ###
